### ISSUE TITLE
small request

### ISSUE THREAD

**Issue by psifertex** [BlackwingHQ/iBoot64Binja#3]
So it makes maintaining the readme slightly more of a pain, but do you mind moving the current contents of the readme into the long_description field of the plugin.json? You can then use [this](https://github.com/Vector35/snippets/blob/master/generate_plugininfo.py) to re-generate the readme. The advantage is that the preview in the plugin manager would then match the github page including (most importantly) the screenshot:

<img width="912" alt="Screen Shot 2020-10-01 at 5 17 32 PM" src="https://user-images.githubusercontent.com/140215/94864449-ff566180-0409-11eb-95b2-f6bebc9aae6e.png">

**Comment by x30n** [comment]
done. Thanks!
I tagged a new release (1.0.1) with the updated plugin.json. Should I file a new ticket on the plugins repo?

**Comment by psifertex** [comment]
Nope, I'll pull it. Thanks!
